---
title: "p8105_hw5_TS3175"
author: "Tanu"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
iris_no_missing = function(x) {
    if (is.numeric(x)) {
      replace_na(x, mean(x, na.rm=TRUE))
    }
    else if (is.character(x)) {
       (replace_na(x, "virginica"))}
  }
```

```{r}
output = map(iris_with_missing, iris_no_missing)
```

# Problem 2

```{r}
df= 
  tibble(participant = list.files(path = "data/", pattern = "csv", all.files = TRUE, full.names = TRUE)) %>% 
    mutate(df = map(participant, read_csv)) %>% 
    unnest()
```

```{r}
df1 =
df %>%
  mutate(
    participant= str_remove(participant, "data//"),
    participant= str_remove(participant, ".csv")
  ) %>% 
pivot_longer(
  week_1:week_8,
  names_to= "week",
  names_prefix = "week_",
  values_to = "obs")  
```

```{r}
df2 =
  df1 %>% 
  mutate(
     participant2= participant
  ) %>% 
    separate(participant, into=c("arm", "subject_id"), sep="_"
          ) 
```

```{r}
df2 %>% 
  ggplot(aes(x= week, y= obs, color= arm, group= participant2)) +
  geom_line() +
  labs(
    title = "Observations Over Time by Group" ,
      x= "Time (Week)",
      y = "Observation"
  )
```

The experimental group had higher observations overtime while the control group experienced about the same observations from begining of the 8 weeks until the end with a slight overall decrese.



